### ISSUE TITLE
The letter A in the Muli font is broken using Microsoft Edge Beta

### ISSUE THREAD

**Issue by dmzza** [google/fonts#2331]
## The Problem
This screenshot is taken from 
Microsoft Edge Beta 
Version 80.0.361.45 (Official build) Beta (64-bit) 
on macOS 10.15.3
<img width="612" alt="Screen Shot 2020-02-04 at 10 47 38 AM" src="https://user-images.githubusercontent.com/120893/73775976-cd3a1600-473b-11ea-87f1-eb1c01c7b691.png">
[![Edit serene-hofstadter-egjg0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/serene-hofstadter-egjg0?fontsize=14&hidenavigation=1&theme=dark)

## Places where it works fine
This problem did not occur on other browsers that I tried (Safari and Chrome). 
It is also interesting to note that this problem does not occur when visiting https://fonts.google.com/specimen/Muli in Microsoft Edge and using `A` as the preview text.

**Comment by m4rc1e** [comment]
Thank you for the test case!

cc @garretrieger

**Comment by garretrieger** [comment]
This should be fixed now.

**Comment by Mushr0000m** [comment]
The issue is still existing with the WOFF version on macOS

**Comment by dmzza** [comment]
The test case I provided appears to be fixed. I'm not sure how I would test it using WOFF. @Mushr0000m could you fork my CodeSandbox to demonstrate the problem?

**Comment by Mushr0000m** [comment]
It looks like it's working with the WOFF version (https://fonts.gstatic.com/s/muli/v20/7Aulp_0qiz-aVz7u3PJLcUMYOFlnl0k30e6fwniDtzM.woff). I don't know why, maybe I had a cache issue because I use it on local. Sorry for the mistake ! 😢

**Comment by bloemendal** [comment]
Still happens for the `ttf` version (latest Chrome on MacOS):
<img width="1364" alt="Screenshot 2020-05-19 at 10 13 32" src="https://user-images.githubusercontent.com/1213240/82302294-b00f1780-99b9-11ea-996b-e7dbccd3491d.png">

**Comment by stan-sack** [comment]
im still seeing this as well. I tried changing to mulish but that also has the issue

**Comment by stan-sack** [comment]
![image](https://user-images.githubusercontent.com/16210936/98454238-6825bc00-21b6-11eb-84e4-33d4355bb55d.png)

**Comment by stan-sack** [comment]
oh wait. its an issues with google-webfonts-helper: https://github.com/majodev/google-webfonts-helper/issues/98
