### ISSUE TITLE
Check Istok

### ISSUE THREAD

**Issue by davelab6** [google/fonts#39]
Following https://github.com/google/fonts/pull/34, check Istok

**Comment by davelab6** [comment]
https://github.com/khaledhosny/ots/issues/99 also relevant to this

**Comment by gregorkaplan** [comment]
While you're there, also check Judson. Same issue, but in all three variants. Istok issue is limited to Bold.

**Comment by adam-iris** [comment]
Why is this still open? The font in Github looks correct, but fonts.google.com is still serving up the broken version.

**Comment by bardware** [comment]
The character they call `LATIN SMALL LETTER U WITH DIAERESIS` - German speakers say ü - is still broken in this git repository.

**Comment by adam-iris** [comment]
Ah, so this is a separate problem from the weight setting in the metadata? Is this a regression error? The fonts.google.com version doesn't seem to have any problem with the ü character (at least to my untrained eye).

It's just frustrating as a user that the BoldItalic issue appears to have been fixed for over a year, but for some reason that fix hasn't been propagated.

**Comment by bardware** [comment]
The `code.google.com` repository still lists some issues. [8](https://code.google.com/archive/p/istok/issues/8), [9](https://code.google.com/archive/p/istok/issues/9) and [10](https://code.google.com/archive/p/istok/issues/10) there are relevant.

**Comment by bardware** [comment]
Still broken here :(
![20161207_google_fonts_istok](https://cloud.githubusercontent.com/assets/802702/20986666/dbe47e98-bcc9-11e6-98be-232f9477a9b1.PNG)

**Comment by fargerio** [comment]
To anyone looking to use the font to print materials: I forked the corresponding repository and published fixes for the ü Issue and also added the capital Ü glyph so all Umlaut characters (äöüÄÖÜ) should behave as expected. 
here is a branch with the fixed ttf files: https://github.com/Klimakoenner/istok/tree/fixed-ttf-files
(the regular repository only contains the .sfd files used by fontforge)

**Comment by laerm0** [comment]
The umlaut issue is fixed, but the bold italic still is the italic.

![screen region 2017-09-19 at 10 51 45](https://user-images.githubusercontent.com/10780161/30598803-c56d7378-9d28-11e7-958f-3c3e01598509.png)

The name and OS/2 table entries for the bold italic are correct, however everything else is identical to the italic, including the outlines. The only source I can find online for Istok is a [development fork](https://github.com/s4ndbox/kotsi) of renamed fonts. There is a directory called "old" that has a correct TTF for the bold italic, though. We could grab it from there.

We should also keep an eye on this fork for the future, too: @alexeiva is on it, so hopefully development will be good. 👍🏻

**Comment by alexeiva** [comment]
Sadly the [Kotsi](https://github.com/s4ndbox/kotsi) development fork is stale, since I didn't gain author's permission to release the update under the original name.

**Comment by laerm0** [comment]
Thanks @alexeiva. So I guess we can just grab those old files and restart our source, yeah?

**Comment by alexeiva** [comment]
To make any changes to Istok fonts please contact original author Andrey V. Panov (panov@canopus.iacp.dvo.ru) and use the [original source repo](https://code.google.com/archive/p/istok/).
