### ISSUE TITLE
Update Playfair Display & Playfair Display SC

### ISSUE THREAD

**Issue by avramchuk** [google/fonts#7]
A cyrillic character «Ы» is wrong in the Playfair Display and Playfair Display SC.

https://www.google.com/fonts/specimen/Playfair+Display
https://www.google.com/fonts/specimen/Playfair+Display+SC

Fixed version is here:
https://github.com/clauseggers/Playfair-Display

**Comment by u3k** [comment]
I do confirm that glyphs are still switched and instead of capital "Ы" it has something like "IЬ"

**Comment by ladytellur** [comment]
The problem exists. 

It should be noted that https://github.com/clauseggers/Playfair-Display font as a solution will not be exactly_the_same google Playfair Display font with the letter "Ы".

clauseggers/Playfair-Display font thinner and lower with the same parameters, as used for google Playfair Display font variant.

**Comment by omerziv** [comment]
Hey @davelab6 - Please update to the latest release to solve this issue.

**Comment by piepaga** [comment]
Hi,
is it possible that not all the font files have been fixed?
With Chrome (which loads the file https://fonts.gstatic.com/s/playfairdisplay/v10/2NBgzUtEeyB-Xtpr9bm1CRw5vVFbIG7DatP53f3SWfE.woff2) I see again the cyrillic character "bI" wrong: capital is still something like "IЬ".

**Comment by aditrif** [comment]
Hello, please update this font family to display correctly the Romanian lowercase characters "ș" and "ț", right now they are distorted. Apparently the correct glyphs are being used on the creator's page here: http://www.forthehearts.net/typeface-design/playfair-display/

**Comment by sandrodz** [comment]
Has not been fixed yet? its 2017.

**Comment by birdkiwi** [comment]
Problem still exists

**Comment by m4rc1e** [comment]
Problem still exists in Playfair Display:

![screen shot 2017-06-14 at 11 58 01](https://user-images.githubusercontent.com/7525512/27129006-bc0eea72-50f8-11e7-9009-74ff0f36f16a.png)

http://jsbin.com/kureverako/edit?html,output

---
It has been solved in Playfair Display SC:

![screen shot 2017-06-14 at 11 59 55](https://user-images.githubusercontent.com/7525512/27129081-fff351f6-50f8-11e7-9587-8d57f1b4170e.png)

http://jsbin.com/rivoyepesa/edit?html,output

**Comment by davelab6** [comment]
@m4rc1e this is urgent, please hotfix only

**Comment by davelab6** [comment]
Fixed

![screen shot 2017-08-29 at 18 56 21](https://user-images.githubusercontent.com/261579/29847874-c65ecdba-8ceb-11e7-9cba-a6ab2a61c6c5.png)
![screen shot 2017-08-29 at 18 56 16](https://user-images.githubusercontent.com/261579/29847873-c65ed4e0-8ceb-11e7-9376-611d0cfc78a4.png)
