### ISSUE TITLE
Quicksand issues with 3 glyphs: » (in bold), ¿ and Œ

### ISSUE THREAD

**Issue by nltesown** [google/fonts#72]
I've noticed two problems with the Quicksand typeface.
- In bold, the glyph **»** (187) is displayed as **«**. I suppose the author forgot to mirror it! The problem doesn't exist in other styles.
- The glyph **Œ** (useful in French when writing about eggs or works of art) has too much space on the right.

See what I mean: http://jsbin.com/macabe/edit?html,css,output

Could this be solved?

**Comment by nltesown** [comment]
I see there hasn't been any feedback on this issue. Could someone confirm whether raising this specific kind of problem belongs here or not?

**Comment by nltesown** [comment]
Thanks for having made an assignment on this. I've just noticed another issue, with the Spanish opening (inverted) question mark, whose orientation is wrong. I've updated my example here: http://jsbin.com/macabe/9/edit?html,css,output

**Comment by nltesown** [comment]
Any hope to see this issue solved, please?

**Comment by nltesown** [comment]
@google-admin @davelab6 Let's bump rather than dump this one. This is a serious issue for all the users of this typeface in French and definitely not up to the quality we all expect from Google Fonts. Now, how is this kind of issue supposed to be solved? By the designer himself?

**Comment by davelab6** [comment]
I agree, this won't be dumped. I believe the designer has fixed this and I need to review and confirm the fix isn't too disruptive and push it. 

The ¿ is also broken, cf https://twitter.com/Marcelo_ads_/status/689840922507485185

**Comment by nltesown** [comment]
Thanks for the good news, Dave! Yes, I also noticed the broken "¿" (my second comment).

**Comment by jsantana90** [comment]
any updates on this? I had to use different font-family only for the ¿ in a `<span>` tag :l

**Comment by nltesown** [comment]
Any update, @davelab6? Has this been solved by the designer and could you review the fix?

**Comment by davelab6** [comment]
I'm still working on some other projects but I will tend to this soon

**Comment by nltesown** [comment]
@davelab6 @omerziv Anything new on this issue? There's been some labelling action lately...

**Comment by ivanskigib** [comment]
This is still unresolved. I am wanting to use this font for a Spanish language website but cannot due to the inverted question mark being the wrong way round. I see this issue has been known for some time, any news as to when the glyph will be uploaded / fixed? 
Thanks

**Comment by davelab6** [comment]
Redesign work has wrapped up, the update will be published soon

https://groups.google.com/forum/#!topic/googlefonts-discuss/XV-VFuB-o24

**Comment by m4rc1e** [comment]
Can confirm the issues have been solved in the versions I am mastering. Expect an update to be rolled out soon.

![screen shot 2016-09-19 at 16 53 39](https://cloud.githubusercontent.com/assets/7525512/18636645/d9e264f8-7e89-11e6-9446-cefa9222e235.png)

![screen shot 2016-09-19 at 16 53 34](https://cloud.githubusercontent.com/assets/7525512/18636651/de7db86e-7e89-11e6-9380-743816d45f8a.png)

Fixed by @ThomasJockin

**Comment by ivanskigib** [comment]
Anyone know when the updates will be available in Google fonts? Would love to use this font on some Spanish websites. Thanks!

**Comment by aaronjpitts** [comment]
Yes these are quite serious issues, especially for Spanish!

**Comment by nltesown** [comment]
OK, so finally this has been solved and the CDN files updated. Wonderful, thanks! But the whole typeface doesn't look like before - the shapes have been slightly altered, it seems. I like this version better, I think, but who can explain what happened?

**Comment by davelab6** [comment]
https://twitter.com/googlefonts/status/806770154155560960

**Comment by davelab6** [comment]
There was also some discussion on twitter about the quality improvement done by @thomasjockin effecting the feel too much, although they agreed the quality was improved:  https://twitter.com/ciaronwalton/status/806877780159905792

**Comment by adri9deu** [comment]
Hey there! In my website is still wrong! What should I do for solving it?

[www.finzauto.com](url)

thanks in advance

**Comment by davelab6** [comment]
Your site seems fine to me; I expect you have the old font files installed.
Please check your fonts installations, and check on a 2nd device (eg
mobile)

**Comment by adri9deu** [comment]
Which browser have you used for checking it? Works fine in safari and chrome, but not in the others. (Specially this symbol ¿).

Could you check it again?

Thanks

**Comment by davelab6** [comment]
Here's firefox:

<img width="1807" alt="screen shot 2017-05-31 at 00 07 40" src="https://cloud.githubusercontent.com/assets/261579/26616468/c86ab3d0-459c-11e7-994d-e87277a1fd9d.png">

**Comment by adri9deu** [comment]
Oh you are right! I thing I already solved the problem but I do not realized because of the browser cache. I deleted the old cache and now looks correctly!

Thanks guys

**Comment by adri9deu** [comment]
sorry, after checking on my computer it is still not working at all, check below:

![image](https://cloud.githubusercontent.com/assets/29067669/26619525/183fe94c-45df-11e7-968f-5453754c54c3.png)


It only looks good on my work computer, which is connected on cloud server. So maybe the reason is the location of IP, could it be?

Please I need help! :(
